### PR TITLE
Fixes and edits to OG-USA blog post

### PR DESCRIPTION
**Pull request by MaxGhenis**

### CODE REVIEW

**Comment by rickecon** [comment]
@MaxGhenis. Thanks for these updates. Two questions.
1. What is the `.github/ISSUE_TEMPLATE/new_post.md` file added by this PR?
2. Didn't I already add the `images/OG-USA_logo_long.png` to this PR? I don't think we need this in your PR.

**Comment by rickecon** [comment]
@MaxGhenis. I like the relative path you updated for the image I put at the beginning of the post. I hope that works. The template I was using for the other image was the [year-in-review post](https://raw.githubusercontent.com/PSLmodels/blog/master/_posts/2020-12-23-2020-year-in-review.md), which used `` to insert the PSL logo at the top.

**Comment by MaxGhenis** [comment]
I think the `new_post.md` was because I synced to master where it exists, shouldn't matter but I deleted it. Also not sure why the image is there but I don't think it matters either? Should I delete it?

I tested the site and the relative image path works.

**Comment by rickecon** [comment]
@MaxGhenis . Yes. Delete the image in your (this) PR, because it duplicates mine. Then I'll merge this. Then I'll make one change in the text of the blog to reflect that the webinar took place on January 11. Then we should be ready to merge into the main blog repository.

**Comment by MaxGhenis** [comment]
OK done

**Pull request merged**
